# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Siyang Sun's Blog
email: siyangsun2007@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a second year student at UCLA, studying some combination of Math and Economics. I am interested in Finance, Computation, Data Science, and Graphic Design. Read more about me on my main page. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://siyangsun.github.io" # the base hostname & protocol for your site
linkedin: LinkedIn
github_username:  siyangsun
cdn_path: https://cloud.githubusercontent.com/assets

# Build settings
markdown: kramdown
